###
POST http://localhost:9000/api/student HTTP/1.1
Content-Type: application/json

{
    "name": "luis",
    "lastName": "Carreon",
    "age": 27,
    "course": ["626fbe1c06eb8f0aa789a08b"]
}

###
GET http://localhost:9000/api/student HTTP/1.1









###
POST http://localhost:9000/api/course HTTP/1.1
Content-Type: application/json

{
    "name": "POO",
    "teacher": "626fbdb4e6c2938199a1c157",
    "day": "Miercoles",
    "hour": "7:00",
    "duration": 1
}

###
GET http://localhost:9000/api/course HTTP/1.1









###
POST http://localhost:9000/api/teacher HTTP/1.1
Content-Type: application/json

{
    "name": "Moises",
    "lastName": "Carmona",
    "age": 39
}

###
GET http://localhost:9000/api/teacher HTTP/1.1



###
PUT http://localhost:9000/api/teacher/626fbdb4e6c2938199a1c157 HTTP/1.1
Content-Type: application/json

{
    "name": "Moises",
    "lastName": "Carmona",
    "age": 40
}